# -*- coding: utf-8 -*-
"""
词库清洗与重新分级脚本
1. 读取现有的 ECDICT 生成的词库
2. 清洗 translation：去掉 \\n、[标签]、重复义项
3. 清洗 pos：标准化词性标注
4. 补充音标（从 ECDICT 原始数据或简单规则）
5. 为小学年级过滤掉过难的词
"""
import json
import os
import re
from pathlib import Path

WORDS_DIR = Path(__file__).parent.parent / "src" / "data" / "words"

# ============================================================
# 小学各年级核心词汇（人教版 PEP 教材精选）
# ============================================================
PRIMARY_WORDS = {
    1: [  # 一年级：最简单的日常词
        ("hello", "你好", "int.", "/həˈloʊ/", "/həˈləʊ/"),
        ("hi", "嗨", "int.", "/haɪ/", "/haɪ/"),
        ("bye", "再见", "int.", "/baɪ/", "/baɪ/"),
        ("goodbye", "再见", "int.", "/ˌɡʊdˈbaɪ/", "/ˌɡʊdˈbaɪ/"),
        ("name", "名字", "n.", "/neɪm/", "/neɪm/"),
        ("book", "书", "n.", "/bʊk/", "/bʊk/"),
        ("bag", "书包", "n.", "/bæɡ/", "/bæɡ/"),
        ("pen", "钢笔", "n.", "/pen/", "/pen/"),
        ("pencil", "铅笔", "n.", "/ˈpensl/", "/ˈpensl/"),
        ("ruler", "尺子", "n.", "/ˈruːlər/", "/ˈruːlə/"),
        ("eraser", "橡皮", "n.", "/ɪˈreɪsər/", "/ɪˈreɪzə/"),
        ("crayon", "蜡笔", "n.", "/ˈkreɪən/", "/ˈkreɪən/"),
        ("school", "学校", "n.", "/skuːl/", "/skuːl/"),
        ("teacher", "老师", "n.", "/ˈtiːtʃər/", "/ˈtiːtʃə/"),
        ("student", "学生", "n.", "/ˈstuːdnt/", "/ˈstjuːdnt/"),
        ("boy", "男孩", "n.", "/bɔɪ/", "/bɔɪ/"),
        ("girl", "女孩", "n.", "/ɡɜːrl/", "/ɡɜːl/"),
        ("friend", "朋友", "n.", "/frend/", "/frend/"),
        ("mom", "妈妈", "n.", "/mɑːm/", "/mɒm/"),
        ("dad", "爸爸", "n.", "/dæd/", "/dæd/"),
        ("cat", "猫", "n.", "/kæt/", "/kæt/"),
        ("dog", "狗", "n.", "/dɔːɡ/", "/dɒɡ/"),
        ("pig", "猪", "n.", "/pɪɡ/", "/pɪɡ/"),
        ("fox", "狐狸", "n.", "/fɑːks/", "/fɒks/"),
        ("bird", "鸟", "n.", "/bɜːrd/", "/bɜːd/"),
        ("fish", "鱼", "n.", "/fɪʃ/", "/fɪʃ/"),
        ("bear", "熊", "n.", "/ber/", "/beə/"),
        ("duck", "鸭子", "n.", "/dʌk/", "/dʌk/"),
        ("apple", "苹果", "n.", "/ˈæpl/", "/ˈæpl/"),
        ("banana", "香蕉", "n.", "/bəˈnænə/", "/bəˈnɑːnə/"),
        ("orange", "橙子", "n.", "/ˈɔːrɪndʒ/", "/ˈɒrɪndʒ/"),
        ("pear", "梨", "n.", "/per/", "/peə/"),
        ("water", "水", "n.", "/ˈwɔːtər/", "/ˈwɔːtə/"),
        ("milk", "牛奶", "n.", "/mɪlk/", "/mɪlk/"),
        ("juice", "果汁", "n.", "/dʒuːs/", "/dʒuːs/"),
        ("cake", "蛋糕", "n.", "/keɪk/", "/keɪk/"),
        ("bread", "面包", "n.", "/bred/", "/bred/"),
        ("egg", "鸡蛋", "n.", "/eɡ/", "/eɡ/"),
        ("rice", "米饭", "n.", "/raɪs/", "/raɪs/"),
        ("one", "一", "num.", "/wʌn/", "/wʌn/"),
        ("two", "二", "num.", "/tuː/", "/tuː/"),
        ("three", "三", "num.", "/θriː/", "/θriː/"),
        ("four", "四", "num.", "/fɔːr/", "/fɔː/"),
        ("five", "五", "num.", "/faɪv/", "/faɪv/"),
        ("six", "六", "num.", "/sɪks/", "/sɪks/"),
        ("seven", "七", "num.", "/ˈsevn/", "/ˈsevn/"),
        ("eight", "八", "num.", "/eɪt/", "/eɪt/"),
        ("nine", "九", "num.", "/naɪn/", "/naɪn/"),
        ("ten", "十", "num.", "/ten/", "/ten/"),
        ("red", "红色的", "adj.", "/red/", "/red/"),
        ("blue", "蓝色的", "adj.", "/bluː/", "/bluː/"),
        ("yellow", "黄色的", "adj.", "/ˈjeloʊ/", "/ˈjeləʊ/"),
        ("green", "绿色的", "adj.", "/ɡriːn/", "/ɡriːn/"),
        ("black", "黑色的", "adj.", "/blæk/", "/blæk/"),
        ("white", "白色的", "adj.", "/waɪt/", "/waɪt/"),
        ("pink", "粉色的", "adj.", "/pɪŋk/", "/pɪŋk/"),
        ("big", "大的", "adj.", "/bɪɡ/", "/bɪɡ/"),
        ("small", "小的", "adj.", "/smɔːl/", "/smɔːl/"),
        ("tall", "高的", "adj.", "/tɔːl/", "/tɔːl/"),
        ("short", "短的;矮的", "adj.", "/ʃɔːrt/", "/ʃɔːt/"),
        ("long", "长的", "adj.", "/lɔːŋ/", "/lɒŋ/"),
        ("good", "好的", "adj.", "/ɡʊd/", "/ɡʊd/"),
        ("bad", "坏的", "adj.", "/bæd/", "/bæd/"),
        ("happy", "开心的", "adj.", "/ˈhæpi/", "/ˈhæpi/"),
        ("sad", "伤心的", "adj.", "/sæd/", "/sæd/"),
        ("hot", "热的", "adj.", "/hɑːt/", "/hɒt/"),
        ("cold", "冷的", "adj.", "/koʊld/", "/kəʊld/"),
        ("new", "新的", "adj.", "/nuː/", "/njuː/"),
        ("old", "老的;旧的", "adj.", "/oʊld/", "/əʊld/"),
        ("eye", "眼睛", "n.", "/aɪ/", "/aɪ/"),
        ("ear", "耳朵", "n.", "/ɪr/", "/ɪə/"),
        ("nose", "鼻子", "n.", "/noʊz/", "/nəʊz/"),
        ("mouth", "嘴巴", "n.", "/maʊθ/", "/maʊθ/"),
        ("hand", "手", "n.", "/hænd/", "/hænd/"),
        ("foot", "脚", "n.", "/fʊt/", "/fʊt/"),
        ("head", "头", "n.", "/hed/", "/hed/"),
        ("hair", "头发", "n.", "/her/", "/heə/"),
        ("face", "脸", "n.", "/feɪs/", "/feɪs/"),
        ("body", "身体", "n.", "/ˈbɑːdi/", "/ˈbɒdi/"),
        ("sun", "太阳", "n.", "/sʌn/", "/sʌn/"),
        ("moon", "月亮", "n.", "/muːn/", "/muːn/"),
        ("star", "星星", "n.", "/stɑːr/", "/stɑː/"),
        ("sky", "天空", "n.", "/skaɪ/", "/skaɪ/"),
        ("tree", "树", "n.", "/triː/", "/triː/"),
        ("flower", "花", "n.", "/ˈflaʊər/", "/ˈflaʊə/"),
        ("house", "房子", "n.", "/haʊs/", "/haʊs/"),
        ("home", "家", "n.", "/hoʊm/", "/həʊm/"),
        ("car", "汽车", "n.", "/kɑːr/", "/kɑː/"),
        ("bus", "公交车", "n.", "/bʌs/", "/bʌs/"),
        ("ball", "球", "n.", "/bɔːl/", "/bɔːl/"),
        ("kite", "风筝", "n.", "/kaɪt/", "/kaɪt/"),
        ("doll", "娃娃", "n.", "/dɑːl/", "/dɒl/"),
        ("run", "跑", "v.", "/rʌn/", "/rʌn/"),
        ("jump", "跳", "v.", "/dʒʌmp/", "/dʒʌmp/"),
        ("swim", "游泳", "v.", "/swɪm/", "/swɪm/"),
        ("fly", "飞", "v.", "/flaɪ/", "/flaɪ/"),
        ("eat", "吃", "v.", "/iːt/", "/iːt/"),
        ("drink", "喝", "v.", "/drɪŋk/", "/drɪŋk/"),
        ("sing", "唱歌", "v.", "/sɪŋ/", "/sɪŋ/"),
        ("dance", "跳舞", "v.", "/dæns/", "/dɑːns/"),
        ("play", "玩", "v.", "/pleɪ/", "/pleɪ/"),
        ("read", "读", "v.", "/riːd/", "/riːd/"),
        ("write", "写", "v.", "/raɪt/", "/raɪt/"),
        ("go", "去", "v.", "/ɡoʊ/", "/ɡəʊ/"),
        ("come", "来", "v.", "/kʌm/", "/kʌm/"),
        ("see", "看见", "v.", "/siː/", "/siː/"),
        ("look", "看", "v.", "/lʊk/", "/lʊk/"),
        ("listen", "听", "v.", "/ˈlɪsn/", "/ˈlɪsn/"),
        ("say", "说", "v.", "/seɪ/", "/seɪ/"),
    ],
    2: [  # 二年级
        ("morning", "早晨", "n.", "/ˈmɔːrnɪŋ/", "/ˈmɔːnɪŋ/"),
        ("afternoon", "下午", "n.", "/ˌæftərˈnuːn/", "/ˌɑːftəˈnuːn/"),
        ("evening", "傍晚", "n.", "/ˈiːvnɪŋ/", "/ˈiːvnɪŋ/"),
        ("night", "夜晚", "n.", "/naɪt/", "/naɪt/"),
        ("day", "天;日", "n.", "/deɪ/", "/deɪ/"),
        ("week", "周;星期", "n.", "/wiːk/", "/wiːk/"),
        ("month", "月", "n.", "/mʌnθ/", "/mʌnθ/"),
        ("year", "年", "n.", "/jɪr/", "/jɪə/"),
        ("today", "今天", "n.", "/təˈdeɪ/", "/təˈdeɪ/"),
        ("yesterday", "昨天", "n.", "/ˈjestərdeɪ/", "/ˈjestədeɪ/"),
        ("tomorrow", "明天", "n.", "/təˈmɔːroʊ/", "/təˈmɒrəʊ/"),
        ("spring", "春天", "n.", "/sprɪŋ/", "/sprɪŋ/"),
        ("summer", "夏天", "n.", "/ˈsʌmər/", "/ˈsʌmə/"),
        ("autumn", "秋天", "n.", "/ˈɔːtəm/", "/ˈɔːtəm/"),
        ("winter", "冬天", "n.", "/ˈwɪntər/", "/ˈwɪntə/"),
        ("rain", "雨", "n.", "/reɪn/", "/reɪn/"),
        ("snow", "雪", "n.", "/snoʊ/", "/snəʊ/"),
        ("wind", "风", "n.", "/wɪnd/", "/wɪnd/"),
        ("cloud", "云", "n.", "/klaʊd/", "/klaʊd/"),
        ("sun", "太阳", "n.", "/sʌn/", "/sʌn/"),
        ("light", "光;灯", "n.", "/laɪt/", "/laɪt/"),
        ("dark", "黑暗的", "adj.", "/dɑːrk/", "/dɑːk/"),
        ("color", "颜色", "n.", "/ˈkʌlər/", "/ˈkʌlə/"),
        ("purple", "紫色的", "adj.", "/ˈpɜːrpl/", "/ˈpɜːpl/"),
        ("brown", "棕色的", "adj.", "/braʊn/", "/braʊn/"),
        ("orange", "橙色的", "adj.", "/ˈɔːrɪndʒ/", "/ˈɒrɪndʒ/"),
        ("family", "家庭", "n.", "/ˈfæməli/", "/ˈfæməli/"),
        ("father", "父亲", "n.", "/ˈfɑːðər/", "/ˈfɑːðə/"),
        ("mother", "母亲", "n.", "/ˈmʌðər/", "/ˈmʌðə/"),
        ("brother", "兄弟", "n.", "/ˈbrʌðər/", "/ˈbrʌðə/"),
        ("sister", "姐妹", "n.", "/ˈsɪstər/", "/ˈsɪstə/"),
        ("baby", "婴儿", "n.", "/ˈbeɪbi/", "/ˈbeɪbi/"),
        ("grandfather", "祖父", "n.", "/ˈɡrænfɑːðər/", "/ˈɡrænfɑːðə/"),
        ("grandmother", "祖母", "n.", "/ˈɡrænmʌðər/", "/ˈɡrænmʌðə/"),
        ("uncle", "叔叔", "n.", "/ˈʌŋkl/", "/ˈʌŋkl/"),
        ("aunt", "阿姨", "n.", "/ænt/", "/ɑːnt/"),
        ("cousin", "表兄弟姐妹", "n.", "/ˈkʌzn/", "/ˈkʌzn/"),
        ("son", "儿子", "n.", "/sʌn/", "/sʌn/"),
        ("daughter", "女儿", "n.", "/ˈdɔːtər/", "/ˈdɔːtə/"),
        ("classroom", "教室", "n.", "/ˈklæsruːm/", "/ˈklɑːsruːm/"),
        ("desk", "课桌", "n.", "/desk/", "/desk/"),
        ("chair", "椅子", "n.", "/tʃer/", "/tʃeə/"),
        ("door", "门", "n.", "/dɔːr/", "/dɔː/"),
        ("window", "窗户", "n.", "/ˈwɪndoʊ/", "/ˈwɪndəʊ/"),
        ("clock", "钟", "n.", "/klɑːk/", "/klɒk/"),
        ("watch", "手表", "n.", "/wɑːtʃ/", "/wɒtʃ/"),
        ("computer", "电脑", "n.", "/kəmˈpjuːtər/", "/kəmˈpjuːtə/"),
        ("phone", "电话", "n.", "/foʊn/", "/fəʊn/"),
        ("hat", "帽子", "n.", "/hæt/", "/hæt/"),
        ("shoe", "鞋子", "n.", "/ʃuː/", "/ʃuː/"),
        ("shirt", "衬衫", "n.", "/ʃɜːrt/", "/ʃɜːt/"),
        ("pants", "裤子", "n.", "/pænts/", "/pænts/"),
        ("dress", "连衣裙", "n.", "/dres/", "/dres/"),
        ("sock", "袜子", "n.", "/sɑːk/", "/sɒk/"),
        ("umbrella", "雨伞", "n.", "/ʌmˈbrelə/", "/ʌmˈbrelə/"),
        ("bottle", "瓶子", "n.", "/ˈbɑːtl/", "/ˈbɒtl/"),
        ("cup", "杯子", "n.", "/kʌp/", "/kʌp/"),
        ("plate", "盘子", "n.", "/pleɪt/", "/pleɪt/"),
        ("bowl", "碗", "n.", "/boʊl/", "/bəʊl/"),
        ("spoon", "勺子", "n.", "/spuːn/", "/spuːn/"),
        ("fork", "叉子", "n.", "/fɔːrk/", "/fɔːk/"),
        ("knife", "刀", "n.", "/naɪf/", "/naɪf/"),
        ("chair", "椅子", "n.", "/tʃer/", "/tʃeə/"),
        ("bed", "床", "n.", "/bed/", "/bed/"),
        ("sofa", "沙发", "n.", "/ˈsoʊfə/", "/ˈsəʊfə/"),
        ("table", "桌子", "n.", "/ˈteɪbl/", "/ˈteɪbl/"),
        ("box", "盒子", "n.", "/bɑːks/", "/bɒks/"),
        ("gift", "礼物", "n.", "/ɡɪft/", "/ɡɪft/"),
        ("money", "钱", "n.", "/ˈmʌni/", "/ˈmʌni/"),
        ("happy", "高兴的", "adj.", "/ˈhæpi/", "/ˈhæpi/"),
        ("angry", "生气的", "adj.", "/ˈæŋɡri/", "/ˈæŋɡri/"),
        ("tired", "累的", "adj.", "/ˈtaɪərd/", "/ˈtaɪəd/"),
        ("hungry", "饿的", "adj.", "/ˈhʌŋɡri/", "/ˈhʌŋɡri/"),
        ("thirsty", "渴的", "adj.", "/ˈθɜːrsti/", "/ˈθɜːsti/"),
        ("sick", "生病的", "adj.", "/sɪk/", "/sɪk/"),
        ("beautiful", "美丽的", "adj.", "/ˈbjuːtɪfl/", "/ˈbjuːtɪfl/"),
        ("ugly", "丑陋的", "adj.", "/ˈʌɡli/", "/ˈʌɡli/"),
        ("clean", "干净的", "adj.", "/kliːn/", "/kliːn/"),
        ("dirty", "脏的", "adj.", "/ˈdɜːrti/", "/ˈdɜːti/"),
        ("fast", "快的", "adj.", "/fæst/", "/fɑːst/"),
        ("slow", "慢的", "adj.", "/sloʊ/", "/sləʊ/"),
        ("easy", "容易的", "adj.", "/ˈiːzi/", "/ˈiːzi/"),
        ("hard", "难的", "adj.", "/hɑːrd/", "/hɑːd/"),
        ("right", "对的", "adj.", "/raɪt/", "/raɪt/"),
        ("wrong", "错的", "adj.", "/rɔːŋ/", "/rɒŋ/"),
        ("open", "打开", "v.", "/ˈoʊpən/", "/ˈəʊpən/"),
        ("close", "关闭", "v.", "/kloʊz/", "/kləʊz/"),
        ("stand", "站", "v.", "/stænd/", "/stænd/"),
        ("sit", "坐", "v.", "/sɪt/", "/sɪt/"),
        ("walk", "走", "v.", "/wɔːk/", "/wɔːk/"),
        ("stop", "停止", "v.", "/stɑːp/", "/stɒp/"),
        ("turn", "转", "v.", "/tɜːrn/", "/tɜːn/"),
        ("push", "推", "v.", "/pʊʃ/", "/pʊʃ/"),
        ("pull", "拉", "v.", "/pʊl/", "/pʊl/"),
        ("carry", "搬运", "v.", "/ˈkæri/", "/ˈkæri/"),
        ("wash", "洗", "v.", "/wɑːʃ/", "/wɒʃ/"),
        ("cook", "做饭", "v.", "/kʊk/", "/kʊk/"),
        ("help", "帮助", "v.", "/help/", "/help/"),
        ("love", "爱", "v.", "/lʌv/", "/lʌv/"),
        ("want", "想要", "v.", "/wɑːnt/", "/wɒnt/"),
        ("need", "需要", "v.", "/niːd/", "/niːd/"),
        ("give", "给", "v.", "/ɡɪv/", "/ɡɪv/"),
        ("take", "拿", "v.", "/teɪk/", "/teɪk/"),
        ("put", "放", "v.", "/pʊt/", "/pʊt/"),
        ("make", "制作", "v.", "/meɪk/", "/meɪk/"),
        ("let", "让", "v.", "/let/", "/let/"),
    ],
    3: [  # 三年级
        ("eleven", "十一", "num.", "/ɪˈlevn/", "/ɪˈlevn/"),
        ("twelve", "十二", "num.", "/twelv/", "/twelv/"),
        ("thirteen", "十三", "num.", "/θɜːrˈtiːn/", "/θɜːˈtiːn/"),
        ("fourteen", "十四", "num.", "/ˌfɔːrˈtiːn/", "/ˌfɔːˈtiːn/"),
        ("fifteen", "十五", "num.", "/ˌfɪfˈtiːn/", "/ˌfɪfˈtiːn/"),
        ("sixteen", "十六", "num.", "/ˌsɪksˈtiːn/", "/ˌsɪksˈtiːn/"),
        ("seventeen", "十七", "num.", "/ˌsevnˈtiːn/", "/ˌsevnˈtiːn/"),
        ("eighteen", "十八", "num.", "/ˌeɪˈtiːn/", "/ˌeɪˈtiːn/"),
        ("nineteen", "十九", "num.", "/ˌnaɪnˈtiːn/", "/ˌnaɪnˈtiːn/"),
        ("twenty", "二十", "num.", "/ˈtwenti/", "/ˈtwenti/"),
        ("thirty", "三十", "num.", "/ˈθɜːrti/", "/ˈθɜːti/"),
        ("forty", "四十", "num.", "/ˈfɔːrti/", "/ˈfɔːti/"),
        ("fifty", "五十", "num.", "/ˈfɪfti/", "/ˈfɪfti/"),
        ("hundred", "一百", "num.", "/ˈhʌndrəd/", "/ˈhʌndrəd/"),
        ("first", "第一", "adj.", "/fɜːrst/", "/fɜːst/"),
        ("second", "第二", "adj.", "/ˈsekənd/", "/ˈsekənd/"),
        ("third", "第三", "adj.", "/θɜːrd/", "/θɜːd/"),
        ("last", "最后的", "adj.", "/læst/", "/lɑːst/"),
        ("next", "下一个", "adj.", "/nekst/", "/nekst/"),
        ("monday", "星期一", "n.", "/ˈmʌndeɪ/", "/ˈmʌndeɪ/"),
        ("tuesday", "星期二", "n.", "/ˈtuːzdeɪ/", "/ˈtjuːzdeɪ/"),
        ("wednesday", "星期三", "n.", "/ˈwenzdeɪ/", "/ˈwenzdeɪ/"),
        ("thursday", "星期四", "n.", "/ˈθɜːrzdeɪ/", "/ˈθɜːzdeɪ/"),
        ("friday", "星期五", "n.", "/ˈfraɪdeɪ/", "/ˈfraɪdeɪ/"),
        ("saturday", "星期六", "n.", "/ˈsætərdeɪ/", "/ˈsætədeɪ/"),
        ("sunday", "星期日", "n.", "/ˈsʌndeɪ/", "/ˈsʌndeɪ/"),
        ("january", "一月", "n.", "/ˈdʒænjueri/", "/ˈdʒænjuəri/"),
        ("february", "二月", "n.", "/ˈfebrueri/", "/ˈfebruəri/"),
        ("march", "三月", "n.", "/mɑːrtʃ/", "/mɑːtʃ/"),
        ("april", "四月", "n.", "/ˈeɪprəl/", "/ˈeɪprəl/"),
        ("may", "五月", "n.", "/meɪ/", "/meɪ/"),
        ("june", "六月", "n.", "/dʒuːn/", "/dʒuːn/"),
        ("july", "七月", "n.", "/dʒuˈlaɪ/", "/dʒuˈlaɪ/"),
        ("august", "八月", "n.", "/ˈɔːɡəst/", "/ˈɔːɡəst/"),
        ("september", "九月", "n.", "/sepˈtembər/", "/sepˈtembə/"),
        ("october", "十月", "n.", "/ɑːkˈtoʊbər/", "/ɒkˈtəʊbə/"),
        ("november", "十一月", "n.", "/noʊˈvembər/", "/nəʊˈvembə/"),
        ("december", "十二月", "n.", "/dɪˈsembər/", "/dɪˈsembə/"),
        ("weather", "天气", "n.", "/ˈweðər/", "/ˈweðə/"),
        ("sunny", "晴朗的", "adj.", "/ˈsʌni/", "/ˈsʌni/"),
        ("rainy", "下雨的", "adj.", "/ˈreɪni/", "/ˈreɪni/"),
        ("cloudy", "多云的", "adj.", "/ˈklaʊdi/", "/ˈklaʊdi/"),
        ("windy", "有风的", "adj.", "/ˈwɪndi/", "/ˈwɪndi/"),
        ("snowy", "下雪的", "adj.", "/ˈsnoʊi/", "/ˈsnəʊi/"),
        ("warm", "温暖的", "adj.", "/wɔːrm/", "/wɔːm/"),
        ("cool", "凉爽的", "adj.", "/kuːl/", "/kuːl/"),
        ("wet", "湿的", "adj.", "/wet/", "/wet/"),
        ("dry", "干的", "adj.", "/draɪ/", "/draɪ/"),
        ("subject", "科目", "n.", "/ˈsʌbdʒɪkt/", "/ˈsʌbdʒɪkt/"),
        ("math", "数学", "n.", "/mæθ/", "/mæθ/"),
        ("english", "英语", "n.", "/ˈɪŋɡlɪʃ/", "/ˈɪŋɡlɪʃ/"),
        ("chinese", "语文;中文", "n.", "/ˌtʃaɪˈniːz/", "/ˌtʃaɪˈniːz/"),
        ("music", "音乐", "n.", "/ˈmjuːzɪk/", "/ˈmjuːzɪk/"),
        ("art", "美术", "n.", "/ɑːrt/", "/ɑːt/"),
        ("science", "科学", "n.", "/ˈsaɪəns/", "/ˈsaɪəns/"),
        ("history", "历史", "n.", "/ˈhɪstəri/", "/ˈhɪstəri/"),
        ("geography", "地理", "n.", "/dʒiˈɑːɡrəfi/", "/dʒiˈɒɡrəfi/"),
        ("piano", "钢琴", "n.", "/piˈænoʊ/", "/piˈænəʊ/"),
        ("guitar", "吉他", "n.", "/ɡɪˈtɑːr/", "/ɡɪˈtɑː/"),
        ("drum", "鼓", "n.", "/drʌm/", "/drʌm/"),
        ("song", "歌曲", "n.", "/sɔːŋ/", "/sɒŋ/"),
        ("picture", "图片", "n.", "/ˈpɪktʃər/", "/ˈpɪktʃə/"),
        ("story", "故事", "n.", "/ˈstɔːri/", "/ˈstɔːri/"),
        ("movie", "电影", "n.", "/ˈmuːvi/", "/ˈmuːvi/"),
        ("game", "游戏", "n.", "/ɡeɪm/", "/ɡeɪm/"),
        ("sport", "运动", "n.", "/spɔːrt/", "/spɔːt/"),
        ("team", "队伍", "n.", "/tiːm/", "/tiːm/"),
        ("winner", "获胜者", "n.", "/ˈwɪnər/", "/ˈwɪnə/"),
        ("prize", "奖品", "n.", "/praɪz/", "/praɪz/"),
        ("gold", "金的", "adj.", "/ɡoʊld/", "/ɡəʊld/"),
        ("silver", "银的", "adj.", "/ˈsɪlvər/", "/ˈsɪlvə/"),
        ("bronze", "铜的", "adj.", "/brɑːnz/", "/brɒnz/"),
        ("farm", "农场", "n.", "/fɑːrm/", "/fɑːm/"),
        ("farmer", "农民", "n.", "/ˈfɑːrmər/", "/ˈfɑːmə/"),
        ("cow", "牛", "n.", "/kaʊ/", "/kaʊ/"),
        ("sheep", "羊", "n.", "/ʃiːp/", "/ʃiːp/"),
        ("horse", "马", "n.", "/hɔːrs/", "/hɔːs/"),
        ("hen", "母鸡", "n.", "/hen/", "/hen/"),
        ("chick", "小鸡", "n.", "/tʃɪk/", "/tʃɪk/"),
        ("egg", "蛋", "n.", "/eɡ/", "/eɡ/"),
        ("grass", "草", "n.", "/ɡræs/", "/ɡrɑːs/"),
        ("leaf", "树叶", "n.", "/liːf/", "/liːf/"),
        ("river", "河", "n.", "/ˈrɪvər/", "/ˈrɪvə/"),
        ("lake", "湖", "n.", "/leɪk/", "/leɪk/"),
        ("sea", "海", "n.", "/siː/", "/siː/"),
        ("boat", "船", "n.", "/boʊt/", "/bəʊt/"),
        ("ship", "轮船", "n.", "/ʃɪp/", "/ʃɪp/"),
        ("train", "火车", "n.", "/treɪn/", "/treɪn/"),
        ("plane", "飞机", "n.", "/pleɪn/", "/pleɪn/"),
        ("bike", "自行车", "n.", "/baɪk/", "/baɪk/"),
        ("road", "路", "n.", "/roʊd/", "/rəʊd/"),
        ("street", "街道", "n.", "/striːt/", "/striːt/"),
        ("city", "城市", "n.", "/ˈsɪti/", "/ˈsɪti/"),
        ("town", "镇", "n.", "/taʊn/", "/taʊn/"),
        ("village", "村庄", "n.", "/ˈvɪlɪdʒ/", "/ˈvɪlɪdʒ/"),
        ("country", "国家", "n.", "/ˈkʌntri/", "/ˈkʌntri/"),
        ("world", "世界", "n.", "/wɜːrld/", "/wɜːld/"),
        ("map", "地图", "n.", "/mæp/", "/mæp/"),
        ("flag", "旗帜", "n.", "/flæɡ/", "/flæɡ/"),
        ("king", "国王", "n.", "/kɪŋ/", "/kɪŋ/"),
        ("queen", "女王", "n.", "/kwiːn/", "/kwiːn/"),
        ("prince", "王子", "n.", "/prɪns/", "/prɪns/"),
        ("princess", "公主", "n.", "/ˈprɪnses/", "/ˈprɪnses/"),
        ("castle", "城堡", "n.", "/ˈkæsl/", "/ˈkɑːsl/"),
        ("crown", "王冠", "n.", "/kraʊn/", "/kraʊn/"),
        ("magic", "魔法", "n.", "/ˈmædʒɪk/", "/ˈmædʒɪk/"),
        ("wizard", "巫师", "n.", "/ˈwɪzərd/", "/ˈwɪzəd/"),
        ("witch", "女巫", "n.", "/wɪtʃ/", "/wɪtʃ/"),
        ("dragon", "龙", "n.", "/ˈdræɡən/", "/ˈdræɡən/"),
        ("fairy", "仙女", "n.", "/ˈferi/", "/ˈfeəri/"),
        ("star", "星星", "n.", "/stɑːr/", "/stɑː/"),
        ("moon", "月亮", "n.", "/muːn/", "/muːn/"),
        ("rocket", "火箭", "n.", "/ˈrɑːkɪt/", "/ˈrɒkɪt/"),
        ("robot", "机器人", "n.", "/ˈroʊbɑːt/", "/ˈrəʊbɒt/"),
    ],
    4: [  # 四年级
        ("breakfast", "早餐", "n.", "/ˈbrekfəst/", "/ˈbrekfəst/"),
        ("lunch", "午餐", "n.", "/lʌntʃ/", "/lʌntʃ/"),
        ("dinner", "晚餐", "n.", "/ˈdɪnər/", "/ˈdɪnə/"),
        ("snack", "零食", "n.", "/snæk/", "/snæk/"),
        ("fruit", "水果", "n.", "/fruːt/", "/fruːt/"),
        ("vegetable", "蔬菜", "n.", "/ˈvedʒtəbl/", "/ˈvedʒtəbl/"),
        ("meat", "肉", "n.", "/miːt/", "/miːt/"),
        ("chicken", "鸡肉", "n.", "/ˈtʃɪkɪn/", "/ˈtʃɪkɪn/"),
        ("beef", "牛肉", "n.", "/biːf/", "/biːf/"),
        ("fish", "鱼肉", "n.", "/fɪʃ/", "/fɪʃ/"),
        ("soup", "汤", "n.", "/suːp/", "/suːp/"),
        ("salad", "沙拉", "n.", "/ˈsæləd/", "/ˈsæləd/"),
        ("noodle", "面条", "n.", "/ˈnuːdl/", "/ˈnuːdl/"),
        ("dumpling", "饺子", "n.", "/ˈdʌmplɪŋ/", "/ˈdʌmplɪŋ/"),
        ("hamburger", "汉堡", "n.", "/ˈhæmbɜːrɡər/", "/ˈhæmbɜːɡə/"),
        ("pizza", "披萨", "n.", "/ˈpiːtsə/", "/ˈpiːtsə/"),
        ("sandwich", "三明治", "n.", "/ˈsænwɪtʃ/", "/ˈsænwɪtʃ/"),
        ("cheese", "奶酪", "n.", "/tʃiːz/", "/tʃiːz/"),
        ("butter", "黄油", "n.", "/ˈbʌtər/", "/ˈbʌtə/"),
        ("sugar", "糖", "n.", "/ˈʃʊɡər/", "/ˈʃʊɡə/"),
        ("salt", "盐", "n.", "/sɔːlt/", "/sɔːlt/"),
        ("pepper", "胡椒", "n.", "/ˈpepər/", "/ˈpepə/"),
        ("chocolate", "巧克力", "n.", "/ˈtʃɑːklət/", "/ˈtʃɒklət/"),
        ("cookie", "饼干", "n.", "/ˈkʊki/", "/ˈkʊki/"),
        ("candy", "糖果", "n.", "/ˈkændi/", "/ˈkændi/"),
        ("icecream", "冰淇淋", "n.", "/ˈaɪskriːm/", "/ˈaɪskriːm/"),
        ("tea", "茶", "n.", "/tiː/", "/tiː/"),
        ("coffee", "咖啡", "n.", "/ˈkɔːfi/", "/ˈkɒfi/"),
        ("lemon", "柠檬", "n.", "/ˈlemən/", "/ˈlemən/"),
        ("grape", "葡萄", "n.", "/ɡreɪp/", "/ɡreɪp/"),
        ("strawberry", "草莓", "n.", "/ˈstrɔːberi/", "/ˈstrɔːbəri/"),
        ("watermelon", "西瓜", "n.", "/ˈwɔːtərmelən/", "/ˈwɔːtəmelən/"),
        ("peach", "桃子", "n.", "/piːtʃ/", "/piːtʃ/"),
        ("mango", "芒果", "n.", "/ˈmæŋɡoʊ/", "/ˈmæŋɡəʊ/"),
        ("tomato", "西红柿", "n.", "/təˈmeɪtoʊ/", "/təˈmɑːtəʊ/"),
        ("potato", "土豆", "n.", "/pəˈteɪtoʊ/", "/pəˈteɪtoʊ/"),
        ("onion", "洋葱", "n.", "/ˈʌnjən/", "/ˈʌnjən/"),
        ("carrot", "胡萝卜", "n.", "/ˈkærət/", "/ˈkærət/"),
        ("cabbage", "卷心菜", "n.", "/ˈkæbɪdʒ/", "/ˈkæbɪdʒ/"),
        ("bean", "豆子", "n.", "/biːn/", "/biːn/"),
        ("corn", "玉米", "n.", "/kɔːrn/", "/kɔːn/"),
        ("mushroom", "蘑菇", "n.", "/ˈmʌʃruːm/", "/ˈmʌʃruːm/"),
        ("oil", "油", "n.", "/ɔɪl/", "/ɔɪl/"),
        ("vinegar", "醋", "n.", "/ˈvɪnɪɡər/", "/ˈvɪnɪɡə/"),
        ("flour", "面粉", "n.", "/ˈflaʊər/", "/ˈflaʊə/"),
        ("bake", "烘焙", "v.", "/beɪk/", "/beɪk/"),
        ("fry", "油炸", "v.", "/fraɪ/", "/fraɪ/"),
        ("boil", "煮沸", "v.", "/bɔɪl/", "/bɔɪl/"),
        ("cut", "切", "v.", "/kʌt/", "/kʌt/"),
        ("mix", "混合", "v.", "/mɪks/", "/mɪks/"),
        ("stir", "搅拌", "v.", "/stɜːr/", "/stɜː/"),
        ("taste", "品尝", "v.", "/teɪst/", "/teɪst/"),
        ("smell", "闻", "v.", "/smel/", "/smel/"),
        ("sweet", "甜的", "adj.", "/swiːt/", "/swiːt/"),
        ("sour", "酸的", "adj.", "/ˈsaʊər/", "/ˈsaʊə/"),
        ("bitter", "苦的", "adj.", "/ˈbɪtər/", "/ˈbɪtə/"),
        ("spicy", "辣的", "adj.", "/ˈspaɪsi/", "/ˈspaɪsi/"),
        ("delicious", "美味的", "adj.", "/dɪˈlɪʃəs/", "/dɪˈlɪʃəs/"),
        ("yummy", "好吃的", "adj.", "/ˈjʌmi/", "/ˈjʌmi/"),
        ("yucky", "难吃的", "adj.", "/ˈjʌki/", "/ˈjʌki/"),
        ("fresh", "新鲜的", "adj.", "/freʃ/", "/freʃ/"),
        ("healthy", "健康的", "adj.", "/ˈhelθi/", "/ˈhelθi/"),
        ("junk", "垃圾", "n.", "/dʒʌŋk/", "/dʒʌŋk/"),
        ("menu", "菜单", "n.", "/ˈmenjuː/", "/ˈmenjuː/"),
        ("order", "点餐", "v.", "/ˈɔːrdər/", "/ˈɔːdə/"),
        ("bill", "账单", "n.", "/bɪl/", "/bɪl/"),
        ("tip", "小费", "n.", "/tɪp/", "/tɪp/"),
        ("waiter", "服务员", "n.", "/ˈweɪtər/", "/ˈweɪtə/"),
        ("cook", "厨师", "n.", "/kʊk/", "/kʊk/"),
        ("kitchen", "厨房", "n.", "/ˈkɪtʃən/", "/ˈkɪtʃən/"),
        ("fridge", "冰箱", "n.", "/frɪdʒ/", "/frɪdʒ/"),
        ("oven", "烤箱", "n.", "/ˈʌvn/", "/ˈʌvn/"),
        ("pot", "锅", "n.", "/pɑːt/", "/pɒt/"),
        ("pan", "平底锅", "n.", "/pæn/", "/pæn/"),
        ("market", "市场", "n.", "/ˈmɑːrkɪt/", "/ˈmɑːkɪt/"),
        ("supermarket", "超市", "n.", "/ˈsuːpərmɑːrkɪt/", "/ˈsuːpəmɑːkɪt/"),
        ("shop", "商店", "n.", "/ʃɑːp/", "/ʃɒp/"),
        ("buy", "买", "v.", "/baɪ/", "/baɪ/"),
        ("sell", "卖", "v.", "/sel/", "/sel/"),
        ("pay", "支付", "v.", "/peɪ/", "/peɪ/"),
        ("cost", "花费", "v.", "/kɔːst/", "/kɒst/"),
        ("cheap", "便宜的", "adj.", "/tʃiːp/", "/tʃiːp/"),
        ("expensive", "昂贵的", "adj.", "/ɪkˈspensɪv/", "/ɪkˈspensɪv/"),
        ("free", "免费的", "adj.", "/friː/", "/friː/"),
        ("dollar", "美元", "n.", "/ˈdɑːlər/", "/ˈdɒlə/"),
        ("cent", "美分", "n.", "/sent/", "/sent/"),
        ("change", "零钱", "n.", "/tʃeɪndʒ/", "/tʃeɪndʒ/"),
        ("receipt", "收据", "n.", "/rɪˈsiːt/", "/rɪˈsiːt/"),
        ("bag", "袋子", "n.", "/bæɡ/", "/bæɡ/"),
        ("wrap", "包装", "v.", "/ræp/", "/ræp/"),
        ("ripe", "熟的", "adj.", "/raɪp/", "/raɪp/"),
        ("raw", "生的", "adj.", "/rɔː/", "/rɔː/"),
        ("peel", "剥皮", "v.", "/piːl/", "/piːl/"),
        ("seed", "种子", "n.", "/siːd/", "/siːd/"),
        ("root", "根", "n.", "/ruːt/", "/ruːt/"),
        ("stem", "茎", "n.", "/stem/", "/stem/"),
        ("branch", "树枝", "n.", "/bræntʃ/", "/brɑːntʃ/"),
        ("trunk", "树干", "n.", "/trʌŋk/", "/trʌŋk/"),
        ("grow", "生长", "v.", "/ɡroʊ/", "/ɡrəʊ/"),
        ("plant", "种植", "v.", "/plænt/", "/plɑːnt/"),
        ("water", "浇水", "v.", "/ˈwɔːtər/", "/ˈwɔːtə/"),
        ("pick", "采摘", "v.", "/pɪk/", "/pɪk/"),
    ],
    5: [  # 五年级：扩展日常生活词汇
        ("aunt", "阿姨", "n.", "/ænt/", "/ɑːnt/"),
        ("uncle", "叔叔", "n.", "/ˈʌŋkl/", "/ˈʌŋkl/"),
        ("cousin", "表兄弟姐妹", "n.", "/ˈkʌzn/", "/ˈkʌzn/"),
        ("neighbor", "邻居", "n.", "/ˈneɪbər/", "/ˈneɪbə/"),
        ("stranger", "陌生人", "n.", "/ˈstreɪndʒər/", "/ˈstreɪndʒə/"),
        ("guest", "客人", "n.", "/ɡest/", "/ɡest/"),
        ("host", "主人", "n.", "/hoʊst/", "/həʊst/"),
        ("people", "人们", "n.", "/ˈpiːpl/", "/ˈpiːpl/"),
        ("child", "孩子", "n.", "/tʃaɪld/", "/tʃaɪld/"),
        ("children", "孩子们", "n.", "/ˈtʃɪldrən/", "/ˈtʃɪldrən/"),
        ("adult", "成年人", "n.", "/əˈdʌlt/", "/ˈædʌlt/"),
        ("man", "男人", "n.", "/mæn/", "/mæn/"),
        ("woman", "女人", "n.", "/ˈwʊmən/", "/ˈwʊmən/"),
        ("policeman", "警察", "n.", "/pəˈliːsmən/", "/pəˈliːsmən/"),
        ("doctor", "医生", "n.", "/ˈdɑːktər/", "/ˈdɒktə/"),
        ("nurse", "护士", "n.", "/nɜːrs/", "/nɜːs/"),
        ("dentist", "牙医", "n.", "/ˈdentɪst/", "/ˈdentɪst/"),
        ("driver", "司机", "n.", "/ˈdraɪvər/", "/ˈdraɪvə/"),
        ("postman", "邮递员", "n.", "/ˈpoʊstmən/", "/ˈpəʊstmən/"),
        ("fireman", "消防员", "n.", "/ˈfaɪərmən/", "/ˈfaɪəmən/"),
        ("pilot", "飞行员", "n.", "/ˈpaɪlət/", "/ˈpaɪlət/"),
        ("singer", "歌手", "n.", "/ˈsɪŋər/", "/ˈsɪŋə/"),
        ("dancer", "舞者", "n.", "/ˈdænsər/", "/ˈdɑːnsə/"),
        ("artist", "艺术家", "n.", "/ˈɑːrtɪst/", "/ˈɑːtɪst/"),
        ("writer", "作家", "n.", "/ˈraɪtər/", "/ˈraɪtə/"),
        ("actor", "演员", "n.", "/ˈæktər/", "/ˈæktə/"),
        ("farmer", "农民", "n.", "/ˈfɑːrmər/", "/ˈfɑːmə/"),
        ("baker", "面包师", "n.", "/ˈbeɪkər/", "/ˈbeɪkə/"),
        ("worker", "工人", "n.", "/ˈwɜːrkər/", "/ˈwɜːkə/"),
        ("sick", "生病的", "adj.", "/sɪk/", "/sɪk/"),
        ("well", "健康的", "adj.", "/wel/", "/wel/"),
        ("medicine", "药", "n.", "/ˈmedsn/", "/ˈmedsn/"),
        ("hospital", "医院", "n.", "/ˈhɑːspɪtl/", "/ˈhɒspɪtl/"),
        ("clinic", "诊所", "n.", "/ˈklɪnɪk/", "/ˈklɪnɪk/"),
        ("pill", "药丸", "n.", "/pɪl/", "/pɪl/"),
        ("checkup", "体检", "n.", "/ˈtʃekʌp/", "/ˈtʃekʌp/"),
        ("cough", "咳嗽", "v.", "/kɔːf/", "/kɒf/"),
        ("fever", "发烧", "n.", "/ˈfiːvər/", "/ˈfiːvə/"),
        ("headache", "头痛", "n.", "/ˈhedeɪk/", "/ˈhedeɪk/"),
        ("stomach", "胃", "n.", "/ˈstʌmək/", "/ˈstʌmək/"),
        ("hurt", "受伤", "v.", "/hɜːrt/", "/hɜːt/"),
        ("rest", "休息", "v.", "/rest/", "/rest/"),
        ("exercise", "锻炼", "v.", "/ˈeksərsaɪz/", "/ˈeksəsaɪz/"),
        ("strong", "强壮的", "adj.", "/strɔːŋ/", "/strɒŋ/"),
        ("weak", "虚弱的", "adj.", "/wiːk/", "/wiːk/"),
        ("careful", "小心的", "adj.", "/ˈkerfl/", "/ˈkeəfl/"),
        ("safe", "安全的", "adj.", "/seɪf/", "/seɪf/"),
        ("danger", "危险", "n.", "/ˈdeɪndʒər/", "/ˈdeɪndʒə/"),
        ("dangerous", "危险的", "adj.", "/ˈdeɪndʒərəs/", "/ˈdeɪndʒərəs/"),
        ("rule", "规则", "n.", "/ruːl/", "/ruːl/"),
        ("follow", "遵守", "v.", "/ˈfɑːloʊ/", "/ˈfɒləʊ/"),
        ("stop", "停止", "v.", "/stɑːp/", "/stɒp/"),
        ("wait", "等待", "v.", "/weɪt/", "/weɪt/"),
        ("cross", "穿过", "v.", "/krɔːs/", "/krɒs/"),
        ("street", "街道", "n.", "/striːt/", "/striːt/"),
        ("light", "灯", "n.", "/laɪt/", "/laɪt/"),
        ("green", "绿灯", "n.", "/ɡriːn/", "/ɡriːn/"),
        ("red", "红灯", "n.", "/red/", "/red/"),
        ("accident", "事故", "n.", "/ˈæksɪdənt/", "/ˈæksɪdənt/"),
        ("fire", "火", "n.", "/ˈfaɪər/", "/ˈfaɪə/"),
        ("smoke", "烟", "n.", "/smoʊk/", "/sməʊk/"),
        ("burn", "燃烧", "v.", "/bɜːrn/", "/bɜːn/"),
        ("call", "呼叫", "v.", "/kɔːl/", "/kɔːl/"),
        ("phone", "电话", "n.", "/foʊn/", "/fəʊn/"),
        ("message", "消息", "n.", "/ˈmesɪdʒ/", "/ˈmesɪdʒ/"),
        ("email", "电子邮件", "n.", "/ˈiːmeɪl/", "/ˈiːmeɪl/"),
        ("letter", "信", "n.", "/ˈletər/", "/ˈletə/"),
        ("postcard", "明信片", "n.", "/ˈpoʊstkɑːrd/", "/ˈpəʊstkɑːd/"),
        ("stamp", "邮票", "n.", "/stæmp/", "/stæmp/"),
        ("address", "地址", "n.", "/əˈdres/", "/əˈdres/"),
        ("mailbox", "信箱", "n.", "/ˈmeɪlbɑːks/", "/ˈmeɪlbɒks/"),
        ("send", "发送", "v.", "/send/", "/send/"),
        ("receive", "收到", "v.", "/rɪˈsiːv/", "/rɪˈsiːv/"),
        ("reply", "回复", "v.", "/rɪˈplaɪ/", "/rɪˈplaɪ/"),
        ("question", "问题", "n.", "/ˈkwestʃən/", "/ˈkwestʃən/"),
        ("answer", "回答", "n.", "/ˈænsər/", "/ˈɑːnsə/"),
        ("ask", "询问", "v.", "/æsk/", "/ɑːsk/"),
        ("tell", "告诉", "v.", "/tel/", "/tel/"),
        ("talk", "谈话", "v.", "/tɔːk/", "/tɔːk/"),
        ("speak", "说话", "v.", "/spiːk/", "/spiːk/"),
        ("hear", "听见", "v.", "/hɪr/", "/hɪə/"),
        ("understand", "理解", "v.", "/ˌʌndərˈstænd/", "/ˌʌndəˈstænd/"),
        ("know", "知道", "v.", "/noʊ/", "/nəʊ/"),
        ("think", "思考", "v.", "/θɪŋk/", "/θɪŋk/"),
        ("remember", "记得", "v.", "/rɪˈmembər/", "/rɪˈmembə/"),
        ("forget", "忘记", "v.", "/fərˈɡet/", "/fəˈɡet/"),
        ("learn", "学习", "v.", "/lɜːrn/", "/lɜːn/"),
        ("teach", "教", "v.", "/tiːtʃ/", "/tiːtʃ/"),
        ("count", "数数", "v.", "/kaʊnt/", "/kaʊnt/"),
        ("add", "加", "v.", "/æd/", "/æd/"),
        ("subtract", "减", "v.", "/səbˈtrækt/", "/səbˈtrækt/"),
        ("multiply", "乘", "v.", "/ˈmʌltɪplaɪ/", "/ˈmʌltɪplaɪ/"),
        ("divide", "除", "v.", "/dɪˈvaɪd/", "/dɪˈvaɪd/"),
        ("number", "数字", "n.", "/ˈnʌmbər/", "/ˈnʌmbə/"),
        ("shape", "形状", "n.", "/ʃeɪp/", "/ʃeɪp/"),
        ("circle", "圆形", "n.", "/ˈsɜːrkl/", "/ˈsɜːkl/"),
        ("square", "正方形", "n.", "/skwer/", "/skweə/"),
        ("triangle", "三角形", "n.", "/ˈtraɪæŋɡl/", "/ˈtraɪæŋɡl/"),
        ("line", "线", "n.", "/laɪn/", "/laɪn/"),
        ("size", "尺寸", "n.", "/saɪz/", "/saɪz/"),
        ("weight", "重量", "n.", "/weɪt/", "/weɪt/"),
        ("heavy", "重的", "adj.", "/ˈhevi/", "/ˈhevi/"),
        ("light", "轻的", "adj.", "/laɪt/", "/laɪt/"),
        ("full", "满的", "adj.", "/fʊl/", "/fʊl/"),
        ("empty", "空的", "adj.", "/ˈempti/", "/ˈempti/"),
        ("same", "相同的", "adj.", "/seɪm/", "/seɪm/"),
        ("different", "不同的", "adj.", "/ˈdɪfrənt/", "/ˈdɪfrənt/"),
        ("important", "重要的", "adj.", "/ɪmˈpɔːrtnt/", "/ɪmˈpɔːtnt/"),
        ("easy", "容易的", "adj.", "/ˈiːzi/", "/ˈiːzi/"),
        ("difficult", "困难的", "adj.", "/ˈdɪfɪkəlt/", "/ˈdɪfɪkəlt/"),
        ("right", "正确的", "adj.", "/raɪt/", "/raɪt/"),
        ("wrong", "错误的", "adj.", "/rɔːŋ/", "/rɒŋ/"),
        ("true", "真实的", "adj.", "/truː/", "/truː/"),
        ("false", "假的", "adj.", "/fɔːls/", "/fɔːls/"),
    ],
    6: [  # 六年级：自然、社会、情感
        ("mountain", "山", "n.", "/ˈmaʊntən/", "/ˈmaʊntən/"),
        ("hill", "小山", "n.", "/hɪl/", "/hɪl/"),
        ("valley", "山谷", "n.", "/ˈvæli/", "/ˈvæli/"),
        ("cliff", "悬崖", "n.", "/klɪf/", "/klɪf/"),
        ("cave", "洞穴", "n.", "/keɪv/", "/keɪv/"),
        ("field", "田野", "n.", "/fiːld/", "/fiːld/"),
        ("wood", "树林", "n.", "/wʊd/", "/wʊd/"),
        ("forest", "森林", "n.", "/ˈfɔːrɪst/", "/ˈfɒrɪst/"),
        ("jungle", "丛林", "n.", "/ˈdʒʌŋɡl/", "/ˈdʒʌŋɡl/"),
        ("desert", "沙漠", "n.", "/ˈdezərt/", "/ˈdezət/"),
        ("island", "岛", "n.", "/ˈaɪlənd/", "/ˈaɪlənd/"),
        ("beach", "海滩", "n.", "/biːtʃ/", "/biːtʃ/"),
        ("sand", "沙子", "n.", "/sænd/", "/sænd/"),
        ("rock", "岩石", "n.", "/rɑːk/", "/rɒk/"),
        ("stone", "石头", "n.", "/stoʊn/", "/stəʊn/"),
        ("dirt", "泥土", "n.", "/dɜːrt/", "/dɜːt/"),
        ("mud", "泥", "n.", "/mʌd/", "/mʌd/"),
        ("pool", "池塘", "n.", "/puːl/", "/puːl/"),
        ("stream", "小溪", "n.", "/striːm/", "/striːm/"),
        ("waterfall", "瀑布", "n.", "/ˈwɔːtərfɔːl/", "/ˈwɔːtəfɔːl/"),
        ("ocean", "海洋", "n.", "/ˈoʊʃn/", "/ˈəʊʃn/"),
        ("wave", "波浪", "n.", "/weɪv/", "/weɪv/"),
        ("shore", "海岸", "n.", "/ʃɔːr/", "/ʃɔː/"),
        ("bay", "海湾", "n.", "/beɪ/", "/beɪ/"),
        ("harbor", "港口", "n.", "/ˈhɑːrbər/", "/ˈhɑːbə/"),
        ("bridge", "桥", "n.", "/brɪdʒ/", "/brɪdʒ/"),
        ("tunnel", "隧道", "n.", "/ˈtʌnl/", "/ˈtʌnl/"),
        ("tower", "塔", "n.", "/ˈtaʊər/", "/ˈtaʊə/"),
        ("church", "教堂", "n.", "/tʃɜːrtʃ/", "/tʃɜːtʃ/"),
        ("palace", "宫殿", "n.", "/ˈpæləs/", "/ˈpæləs/"),
        ("museum", "博物馆", "n.", "/mjuːˈziːəm/", "/mjuːˈziːəm/"),
        ("library", "图书馆", "n.", "/ˈlaɪbreri/", "/ˈlaɪbrəri/"),
        ("cinema", "电影院", "n.", "/ˈsɪnəmə/", "/ˈsɪnəmə/"),
        ("theater", "剧院", "n.", "/ˈθiːətər/", "/ˈθɪətə/"),
        ("circus", "马戏团", "n.", "/ˈsɜːrkəs/", "/ˈsɜːkəs/"),
        ("zoo", "动物园", "n.", "/zuː/", "/zuː/"),
        ("park", "公园", "n.", "/pɑːrk/", "/pɑːk/"),
        ("garden", "花园", "n.", "/ˈɡɑːrdn/", "/ˈɡɑːdn/"),
        ("yard", "院子", "n.", "/jɑːrd/", "/jɑːd/"),
        ("fence", "篱笆", "n.", "/fens/", "/fens/"),
        ("gate", "大门", "n.", "/ɡeɪt/", "/ɡeɪt/"),
        ("path", "小路", "n.", "/pæθ/", "/pɑːθ/"),
        ("road", "路", "n.", "/roʊd/", "/rəʊd/"),
        ("corner", "角落", "n.", "/ˈkɔːrnər/", "/ˈkɔːnə/"),
        ("center", "中心", "n.", "/ˈsentər/", "/ˈsentə/"),
        ("edge", "边缘", "n.", "/edʒ/", "/edʒ/"),
        ("top", "顶部", "n.", "/tɑːp/", "/tɒp/"),
        ("bottom", "底部", "n.", "/ˈbɑːtəm/", "/ˈbɒtəm/"),
        ("left", "左边", "n.", "/left/", "/left/"),
        ("right", "右边", "n.", "/raɪt/", "/raɪt/"),
        ("north", "北方", "n.", "/nɔːrθ/", "/nɔːθ/"),
        ("south", "南方", "n.", "/saʊθ/", "/saʊθ/"),
        ("east", "东方", "n.", "/iːst/", "/iːst/"),
        ("west", "西方", "n.", "/west/", "/west/"),
        ("map", "地图", "n.", "/mæp/", "/mæp/"),
        ("compass", "指南针", "n.", "/ˈkʌmpəs/", "/ˈkʌmpəs/"),
        ("direction", "方向", "n.", "/dəˈrekʃn/", "/dəˈrekʃn/"),
        ("weather", "天气", "n.", "/ˈweðər/", "/ˈweðə/"),
        ("season", "季节", "n.", "/ˈsiːzn/", "/ˈsiːzn/"),
        ("nature", "大自然", "n.", "/ˈneɪtʃər/", "/ˈneɪtʃə/"),
        ("environment", "环境", "n.", "/ɪnˈvaɪrənmənt/", "/ɪnˈvaɪrənmənt/"),
        ("earth", "地球", "n.", "/ɜːrθ/", "/ɜːθ/"),
        ("planet", "行星", "n.", "/ˈplænɪt/", "/ˈplænɪt/"),
        ("space", "太空", "n.", "/speɪs/", "/speɪs/"),
        ("sky", "天空", "n.", "/skaɪ/", "/skaɪ/"),
        ("cloud", "云", "n.", "/klaʊd/", "/klaʊd/"),
        ("fog", "雾", "n.", "/fɑːɡ/", "/fɒɡ/"),
        ("ice", "冰", "n.", "/aɪs/", "/aɪs/"),
        ("steam", "蒸汽", "n.", "/stiːm/", "/stiːm/"),
        ("rainbow", "彩虹", "n.", "/ˈreɪnboʊ/", "/ˈreɪnbəʊ/"),
        ("lightning", "闪电", "n.", "/ˈlaɪtnɪŋ/", "/ˈlaɪtnɪŋ/"),
        ("thunder", "雷", "n.", "/ˈθʌndər/", "/ˈθʌndə/"),
        ("storm", "暴风雨", "n.", "/stɔːrm/", "/stɔːm/"),
        ("earthquake", "地震", "n.", "/ˈɜːrθkweɪk/", "/ˈɜːθkweɪk/"),
        ("volcano", "火山", "n.", "/vɑːlˈkeɪnoʊ/", "/vɒlˈkeɪnəʊ/"),
        ("magic", "魔法", "n.", "/ˈmædʒɪk/", "/ˈmædʒɪk/"),
        ("dream", "梦想", "n.", "/driːm/", "/driːm/"),
        ("wish", "愿望", "n.", "/wɪʃ/", "/wɪʃ/"),
        ("hope", "希望", "n.", "/hoʊp/", "/həʊp/"),
        ("luck", "运气", "n.", "/lʌk/", "/lʌk/"),
        ("happy", "快乐的", "adj.", "/ˈhæpi/", "/ˈhæpi/"),
        ("sad", "悲伤的", "adj.", "/sæd/", "/sæd/"),
        ("angry", "生气的", "adj.", "/ˈæŋɡri/", "/ˈæŋɡri/"),
        ("excited", "兴奋的", "adj.", "/ɪkˈsaɪtɪd/", "/ɪkˈsaɪtɪd/"),
        ("scared", "害怕的", "adj.", "/skerd/", "/skeəd/"),
        ("surprised", "惊讶的", "adj.", "/sərˈpraɪzd/", "/səˈpraɪzd/"),
        ("bored", "无聊的", "adj.", "/bɔːrd/", "/bɔːd/"),
        ("lonely", "孤独的", "adj.", "/ˈloʊnli/", "/ˈləʊnli/"),
        ("proud", "骄傲的", "adj.", "/praʊd/", "/praʊd/"),
        ("shy", "害羞的", "adj.", "/ʃaɪ/", "/ʃaɪ/"),
        ("brave", "勇敢的", "adj.", "/breɪv/", "/breɪv/"),
        ("kind", "善良的", "adj.", "/kaɪnd/", "/kaɪnd/"),
        ("friendly", "友好的", "adj.", "/ˈfrendli/", "/ˈfrendli/"),
        ("honest", "诚实的", "adj.", "/ˈɑːnɪst/", "/ˈɒnɪst/"),
        ("rude", "粗鲁的", "adj.", "/ruːd/", "/ruːd/"),
        ("polite", "礼貌的", "adj.", "/pəˈlaɪt/", "/pəˈlaɪt/"),
        ("quiet", "安静的", "adj.", "/ˈkwaɪət/", "/ˈkwaɪət/"),
        ("loud", "大声的", "adj.", "/laʊd/", "/laʊd/"),
        ("funny", "有趣的", "adj.", "/ˈfʌni/", "/ˈfʌni/"),
        ("serious", "严肃的", "adj.", "/ˈsɪriəs/", "/ˈsɪriəs/"),
        ("smart", "聪明的", "adj.", "/smɑːrt/", "/smɑːt/"),
        ("foolish", "愚蠢的", "adj.", "/ˈfuːlɪʃ/", "/ˈfuːlɪʃ/"),
    ],
}

# 5-6年级、初中、高中、大学使用清洗后的ECDICT数据
# 先生成1-4年级的精选数据，其余从ECDICT清洗

def clean_translation(trans: str) -> str:
    """清洗翻译：去掉 \\n [标签] 词性前缀 重复义项"""
    if not trans:
        return ""
    # 去掉 \\n 字面量（JSON中存储的）
    t = trans.replace("\\n", "；").replace("\n", "；")
    # 去掉 [xxx] 标签
    t = re.sub(r'\[[^\]]*\]', '', t)
    # 去掉词性前缀如 "n. " "v. " "adj. " "a. " "adv. "
    t = re.sub(r'^[a-z]+\.\s*', '', t.strip())
    parts = t.split('；')
    cleaned = []
    seen = set()
    for p in parts:
        p = p.strip().strip('；,，').strip()
        # 再次去掉每个义项开头的词性前缀
        p = re.sub(r'^[a-z]+\.\s*', '', p)
        if not p:
            continue
        if p in seen:
            continue
        seen.add(p)
        cleaned.append(p)
    return '；'.join(cleaned[:3])

def clean_pos(pos: str) -> str:
    """标准化词性"""
    if not pos:
        return ""
    p = pos.strip()
    # 统一格式
    if p.startswith('n'):
        return 'n.'
    if p.startswith('v'):
        return 'v.'
    if p.startswith('adj') or p.startswith('a.'):
        return 'adj.'
    if p.startswith('adv'):
        return 'adv.'
    if p.startswith('pron'):
        return 'pron.'
    if p.startswith('prep'):
        return 'prep.'
    if p.startswith('conj'):
        return 'conj.'
    if p.startswith('int') or p.startswith('interj'):
        return 'int.'
    if p.startswith('num'):
        return 'num.'
    if p.startswith('art'):
        return 'art.'
    return p

def make_word_entry(word, translation, pos, phon_us, phon_uk, grade, tag):
    return {
        "word": word,
        "phonetic_us": phon_us or "",
        "phonetic_uk": phon_uk or "",
        "translation": translation,
        "pos": pos or "",
        "example_en": "",
        "example_cn": "",
        "high_freq_points": "",
        "sentence_analysis": "",
        "grade": grade,
        "tag": tag,
    }

def process_primary_grades():
    """处理小学1-6年级：使用精选词汇表"""
    for grade, words in PRIMARY_WORDS.items():
        entries = []
        for w, trans, pos, us, uk in words:
            entries.append(make_word_entry(w, trans, pos, us, uk, grade, "primary"))
        out = WORDS_DIR / f"grade_{grade}.json"
        with open(out, 'w', encoding='utf-8') as f:
            json.dump(entries, f, ensure_ascii=False, indent=2)
        print(f"  grade_{grade}.json: {len(entries)} 个单词（精选）")

def process_other_grades():
    """处理其他年级（7-17）：清洗ECDICT原数据"""
    for grade in range(7, 18):
        src = WORDS_DIR / f"grade_{grade}.json"
        if not src.exists():
            print(f"  grade_{grade}.json: 不存在，跳过")
            continue
        with open(src, 'r', encoding='utf-8') as f:
            words = json.load(f)
        cleaned = []
        for w in words:
            trans = clean_translation(w.get('translation', ''))
            pos = clean_pos(w.get('pos', ''))
            if not trans or not w.get('word'):
                continue
            entry = make_word_entry(
                w['word'],
                trans,
                pos,
                w.get('phonetic_us', ''),
                w.get('phonetic_uk', ''),
                grade,
                w.get('tag', '')
            )
            cleaned.append(entry)
        with open(src, 'w', encoding='utf-8') as f:
            json.dump(cleaned, f, ensure_ascii=False, indent=2)
        print(f"  grade_{grade}.json: {len(cleaned)} 个单词（清洗后）")

if __name__ == '__main__':
    print("=" * 60)
    print("  词库清洗与重新分级")
    print("=" * 60)
    print("\n[1/2] 处理小学1-6年级（精选词汇表）...")
    process_primary_grades()
    print("\n[2/2] 处理7-17年级（清洗ECDICT数据）...")
    process_other_grades()
    print("\n" + "=" * 60)
    print("  完成！")
    print("=" * 60)
